### PR TITLE
fix bug causing custom error message not to show when datepicker has value, fix datepicker test

### PR DESCRIPTION
**Pull request by Sotruong-copart**

### CODE REVIEW

**Comment by Sotruong-copart** [comment]
FYI, the datepicker test was failing even before I made my changes. I updated the test to get it to pass. Had to add setTimeout to get it to work. I thinking add setTimeout allows time for the page to rerender before checking value.

**Comment by colshacol** [comment]
They're still failing, friend!

**Comment by Sotruong-copart** [comment]
The datepicker tests are passing. The other tests are failing such as AppBar and Filter. I did not fix those since it wasn't related to the datepicker. This pull request was only datepicker related.

Did you want me to fix the other test before you approved?

**Comment by colshacol** [comment]
I have fixed the tests in #164. About to push. Once that one merges, I will merge master into yours, ensure everything is working fine, and get it merged. :+1:

**Pull request merged**
